# -- Site Configuration --
baseURL = 'https://blog.watchstep.me/'
languageCode = 'en'
title = "watchstep's blog"
theme = 'blowfish'
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true
paginate = 10
summaryLength = 30

#googleAnalytics = "G-XXXXXXXXX"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]