[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = '© 2025 • <a href="https://blog.watchstep.me" class="text-muted">watchstep</a>'
    alertText = '🚀 Welcome to Watchstep Blog!'

