languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "watchstep"
logo = "img/logo.png"
description = "watchstep's blog"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"


[author]
  image = "img/logo.png"
  links = [
    {email = 'mailto:cathy033077@yonsei.ac.kr'},
    {link = 'https://watchstep.me/'},
    {github = 'https://github.com/watchstep'},
  ]
  name = "watchstep's blog"
  headline = "Welcome to My blog! I'm Interested in ML & Flutter"
  bio = "일개 학부생입니다."
  