baseURL = 'https://blog.watchstep.me/'
languageCode = 'en'
title = 'watchstep's blog'
theme = 'blowfish'
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 30

# googleAnalytics = "G-XXXXXXXXX"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[author]
  name = 'watchstep'
  headline = 'Watch Your Step!'